### ISSUE TITLE
module 'torch' has no attribute 'rfft'

### ISSUE THREAD

**Issue by aoliao12138** [zh217/torch-dct#26]
When I try to run the example, I get a runtime error
```
>>> X = dct.dct(x)   # DCT-II done through the last dimension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch_dct/_dct.py", line 48, in dct
    Vc = torch.rfft(v, 1, onesided=False)
AttributeError: module 'torch' has no attribute 'rfft'
```

my torch version is '1.10.2+cu113'. Did I miss something?

Also, I want to ask what is scaled DCT? Does the input of scaled DCT need to be in range [0,1]?

Thank you very much!

**Comment by yrj1409** [comment]
'torch.rfft' is removed after torch1.9

**Comment by RobinHistory** [comment]
Thanks for the solution @MaloShady .
But I have a question.
In dct1(): return torch.rfft(torch.cat([x, x.flip([1])[:, 1:-1]], dim=1), 1)[:, :, 0].view(*x_shape).
Since new torch use fft to replace rfft, why this one doesn't raise a bug of no module named rfft.
Should we change torch.rfft to torch.fft.rfft?

**Comment by jonnor** [comment]
This can be closed now. Fixed in PR https://github.com/zh217/torch-dct/pull/24
